title: Cellule de Bioinformatique du BRIC
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

description: Présentation de la cellule ODIL
